name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['6.0.x', '7.0.x']
    steps:
    - uses: actions/checkout@v3
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: {{ matrix.dotnet }}
    - uses: education/autograding@v1